- Makefile
Rsync-like operation of cp must be an osx feature, linux needs the asterisk
> Fix build on linux.

- Makefile
Same situation as with PHP Library -- updates to point to DOP-owned AWS buckets rather than the monolithic 10gen-noc bucket. Again, it would be great if y'all can backport to the other versions of the driver docs and then republish.
> Update Makefile to publish to DOP-owned AWS buckets.

- config/redirects
This adds redirects to avoid broken links that were introduced in https://github.com/mongodb/mongo-ruby-driver/pull/2226 and reported in [DOCSP-18655](https://jira.mongodb.org/browse/DOCSP-18655)
> adds redirects

- .gitmodules
- Makefile
- snooty.toml
- worker.sh
**Important note**: we have done *nothing* to handle the generation of the API docs using yarn. We will need to coordinate with the Ruby driver engineers to sort out a solution to the generation of those API docs since it doesn't really make sense for it to go through the Autobuilder / be part of this repo anymore.
Once this PR is merged, the `master` branch of docs-ruby will be deployable using the /deploy command and build with snooty.
> DOP-3397: set up docs-ruby to build with Snooty

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-31844
Can't test staging, but here are the mut output for the new redirects:
```
Redirect 301 /docs/ruby-driver https://www.mongodb.com/docs/ruby-driver/current/
Redirect 301 /docs/ruby-driver/v1.x/ https://www.mongodb.com/docs/ruby-driver/current/
Redirect 301 /docs/ruby-driver/v1.x/aggregation-framework/ https://www.mongodb.com/docs/ruby-driver/current/
Redirect 301 /docs/ruby-driver/v1.x/authentication/ https://www.mongodb.com/docs/ruby-driver/current/
Redirect 301 /docs/ruby-driver/v1.x/bulk-write-operations/ https://www.mongodb.com/docs/ruby-driver/current/
Redirect 301 /docs/ruby-driver/v1.x/credits/ https://www.mongodb.com/docs/ruby-driver/current/
Redirect 301 /docs/ruby-driver/v1.x/examples/ …
```
> DOCSP-31844: redirect all v1.x to current homepage

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/ruby-driver/DOCSP-37038/reference/create-client/
Output from git submodule status:
```
+04602accc42dc4efb16b2171f134993e2864a3fc bson-ruby (v5.0.0)
+e459c3f75f1b1a2181b8d468751580664a3e9e04 mongo-ruby-driver (v2.19.1-43-ge459c3f75)
```
Output from git log on mongo-ruby-driver:
```
commit e459c3f75f1b1a2181b8d468751580664a3e9e04 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: Nora Reidy <nora.reidy@mongodb.com>
Date:   Thu Feb 22 11:34:23 2024 -0500
DOCSP-37038: Fix broken link (#2841)
...
```
> DOCSP-37038: Fix broken link (staging)

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37137
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/ruby-driver/DOCSP-37137/
Output from git submodule status:
`517891b56c5e7ef1fd25e825a0c8ff4e3afd5d84 mongo-ruby-driver (v2.19.3-3-g517891b56)`
Output from git hist (on mongo-ruby-driver):
`[2024-02-28] [517891b56] | DOCSP-37137: Update BSON page references (#2844) {{Nora Reidy}}`
> DOCSP-37137: Fix BSON references (staging)

- config/redirects
JIRA - [DOCSP-38366](https://jira.mongodb.org/browse/DOCSP-38366)
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/ruby-driver/DOCSP-38366-fix-redirects/>
MUT output:
```
Redirect 301 /docs/ruby-driver/v2.16/tutorials/ruby-driver-client-side-encryption https://www.mongodb.com/docs/ruby-driver/v2.16/reference/in-use-encryption/client-side-encryption/
Redirect 301 /docs/ruby-driver/v2.17/tutorials/ruby-driver-client-side-encryption https://www.mongodb.com/docs/ruby-driver/v2.17/reference/in-use-encryption/client-side-encryption/
Redirect 301 /docs/ruby-driver/v2.18/tutorials/ruby-driver-client-side-encryption https://www.mongodb.com/docs/ruby-driver/v2.18/reference/in-use-encryption/client-side-e …
```
> DOCSP-38366: Fix redirects

- source/reference/driver-compatibility.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42091
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/ruby-driver/DOCSP-42091-add-v8/reference/driver-compatibility/
- [] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
> DOCSP-42091 Add 8.0 to compatibility table

- source/reference/create-client.txt
- source/reference/crud-operations.txt
- source/reference/in-use-encryption/client-side-encryption.txt
- source/reference/monitoring.txt
Specifications files were converted from rst to md. Rename rst links to md in [4 files](https://github.com/search?q=%28repo%3Amongodb%2Fdocs-ruby%29+%28%22https%3A%2F%2Fgithub.com%2Fmongodb%2Fspecifications%22+AND+%22.rst%22%29&type=code). 
- [Monitoring](https://deploy-preview-75--docs-ruby.netlify.app/reference/monitoring/)
- [Client-Side Encryption](https://deploy-preview-75--docs-ruby.netlify.app/reference/in-use-encryption/client-side-encryption/)
- [Creating a Client](https://deploy-preview-75--docs-ruby.netlify.app/reference/create-client/)
- [CRUD Operations](https://deploy-preview-75--docs-ruby.netlify.app/reference/crud-operations/)
> (DOSCP-44189) [Ruby] Rename Specifications Links from RST to MD

- source/reference/create-client.txt
- source/reference/crud-operations.txt
- source/reference/in-use-encryption/client-side-encryption.txt
- source/reference/monitoring.txt
Specifications files were converted from rst to md. Rename rst links to md in [4 files](https://github.com/search?q=%28repo%3Amongodb%2Fdocs-ruby%29+%28%22https%3A%2F%2Fgithub.com%2Fmongodb%2Fspecifications%22+AND+%22.rst%22%29&type=code). 
- [Monitoring](https://deploy-preview-75--docs-ruby.netlify.app/reference/monitoring/)
- [Client-Side Encryption](https://deploy-preview-75--docs-ruby.netlify.app/reference/in-use-encryption/client-side-encryption/)
- [Creating a Client](https://deploy-preview-75--docs-ruby.netlify.app/reference/create-client/)
- [CRUD Operations](https://deploy-preview-75--docs-ruby.netlify.app/reference/crud-operations/)
> (DOSCP-44189) Backport DOCSP-44189 to v2.21

- source/reference/create-client.txt
- source/reference/crud-operations.txt
- source/reference/in-use-encryption/client-side-encryption.txt
- source/reference/monitoring.txt
Specifications files were converted from rst to md. Rename rst links to md in [4 files](https://github.com/search?q=%28repo%3Amongodb%2Fdocs-ruby%29+%28%22https%3A%2F%2Fgithub.com%2Fmongodb%2Fspecifications%22+AND+%22.rst%22%29&type=code). 
- [Monitoring](https://deploy-preview-75--docs-ruby.netlify.app/reference/monitoring/)
- [Client-Side Encryption](https://deploy-preview-75--docs-ruby.netlify.app/reference/in-use-encryption/client-side-encryption/)
- [Creating a Client](https://deploy-preview-75--docs-ruby.netlify.app/reference/create-client/)
- [CRUD Operations](https://deploy-preview-75--docs-ruby.netlify.app/reference/crud-operations/)
> (DOSCP-44189) Backport DOCSP-44189 to v2.20

- source/getting-started.txt
- source/index.txt
- source/reference/connection-and-configuration.txt
- source/reference/in-use-encryption.txt
- source/reference/schema-operations.txt
- source/reference/working-with-data.txt
- source/tutorials.txt
Jira: https://jira.mongodb.org/browse/DOCSP-44950
Staging: https://deploy-preview-83--docs-ruby.netlify.app/
> DOCSP-44950 TOC Relabel

- snooty.toml
- source/get-started.txt
- source/get-started/download-and-install.txt
- source/includes/get-started/troubleshoot.rst
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45171 and https://jira.mongodb.org/browse/DOCSP-45172
<li><a href=https://deploy-preview-92--docs-ruby.netlify.app/get-started>get-started</a></li><li><a href=https://deploy-preview-92--docs-ruby.netlify.app/get-started/download-and-install>get-started/download-and-install</a></li><li><a href=https://deploy-preview-92--docs-ruby.netlify.app/index>index</a></li>
> DOCSP-45171: Download and Install

- source/get-started/create-a-connection-string.txt
- source/get-started/create-a-deployment.txt
- source/includes/read/retrieve.rb
- source/index.txt
- source/read.txt
- source/read/retrieve.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45194
<li><a href=https://deploy-preview-96--docs-ruby.netlify.app/read>read</a></li><li><a href=https://deploy-preview-96--docs-ruby.netlify.app/read/retrieve>read/retrieve</a></li><li><a href=https://deploy-preview-96--docs-ruby.netlify.app/get-started/create-a-connection-string>get-started/create-a-connection-string</a></li><li><a href=https://deploy-preview-96--docs-ruby.netlify.app/get-started/create-a-deployment>get-started/create-a-deployment</a></li><li><a href=https://deploy-preview-96--docs-ruby.netlify.app/index>index</a></li>
> DOCSP-45194: Retrieve data

- source/includes/write/insert.rb
- source/write/insert.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45186>
<li><a href=https://deploy-preview-101--docs-ruby.netlify.app/write/insert>write/insert</a></li>
> DOCSP-45186: Insert

- snooty.toml
- source/reference/transactions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45880
<li><a href=https://deploy-preview-107--docs-ruby.netlify.app/reference/transactions>reference/transactions</a></li>
- [N/A] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
> DOCSP-45880 Add parallel operations note

- source/includes/read/project.rb
- source/read.txt
- source/read/project.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45195
<li><a href=https://deploy-preview-105--docs-ruby.netlify.app/read/project>read/project</a></li><li><a href=https://deploy-preview-105--docs-ruby.netlify.app/read>read</a></li>
> DOCSP-45195: Project fields

- source/includes/read/limit-skip-sort.rb
- source/read.txt
- source/read/specify-documents-to-return.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45196
<li><a href=https://deploy-preview-109--docs-ruby.netlify.app/read/specify-documents-to-return>read/specify-documents-to-return</a></li><li><a href=https://deploy-preview-109--docs-ruby.netlify.app/read>read</a></li>
> DOCSP-45196: Limit, skip, and sort

- source/includes/write/replace.rb
- source/write/replace.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45188>
<li><a href=https://deploy-preview-108--docs-ruby.netlify.app/write/replace>write/replace</a></li>
> DOCSP-45188: Replace

- source/includes/indexes/compound.rb
- source/indexes.txt
- source/indexes/compound-index.txt
- source/indexes/single-field-index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45204>
<li><a href=https://deploy-preview-106--docs-ruby.netlify.app/indexes/compound-index>indexes/compound-index</a></li><li><a href=https://deploy-preview-106--docs-ruby.netlify.app/indexes>indexes</a></li><li><a href=https://deploy-preview-106--docs-ruby.netlify.app/indexes/single-field-index>indexes/single-field-index</a></li>
> DOCSP-45204 Compound Index

- source/includes/usage-examples/sample-app-intro.rst
- source/includes/usage-examples/sample-app.rb
- source/includes/usage-examples/write-code-examples.rb
- source/includes/write/delete.rb
- source/includes/write/insert.rb
- source/includes/write/update.rb
- source/write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45185>
<li><a href=https://deploy-preview-114--docs-ruby.netlify.app/write>write</a></li>
> DOCSP-45185: Write landing page

- source/includes/write/transaction.rb
- source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45214>
<li><a href=https://deploy-preview-115--docs-ruby.netlify.app/write/transactions>write/transactions</a></li>
> DOCSP-45214 Add transactions

- source/includes/read/cursors.rb
- source/read.txt
- source/read/cursors.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45199
<li><a href=https://deploy-preview-120--docs-ruby.netlify.app/read/cursors>read/cursors</a></li><li><a href=https://deploy-preview-120--docs-ruby.netlify.app/read>read</a></li>
> DOCSP-45199: Cursors

- source/includes/usage-examples/read-code-examples.rb
- source/includes/usage-examples/sample-app-intro.rst
- source/includes/usage-examples/sample-read-app.rb
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45192>
<li><a href=https://deploy-preview-128--docs-ruby.netlify.app/read>read</a></li>
> DOCSP-45192-read-data-page

- source/data-formats.txt
- source/data-formats/time-series.txt
- source/includes/usage-examples/time-series.rb
- source/index.txt
- source/time-series.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45183>
<li><a href=https://deploy-preview-121--docs-ruby.netlify.app/data-formats>data-formats</a></li><li><a href=https://deploy-preview-121--docs-ruby.netlify.app/data-formats/time-series>data-formats/time-series</a></li><li><a href=https://deploy-preview-121--docs-ruby.netlify.app/index>index</a></li>
> DOCSP-45183-time-series-collections

- source/includes/read/change-streams.rb
- source/read.txt
- source/read/change-streams.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45200
<li><a href=https://deploy-preview-123--docs-ruby.netlify.app/read/change-streams>read/change-streams</a></li><li><a href=https://deploy-preview-123--docs-ruby.netlify.app/read>read</a></li>
> DOCSP-45200: Change streams

- snooty.toml
- source/databases-collection.txt
- source/databases-collections/run-command.txt
- source/includes/databases-collections/run-command.rb
- source/write/delete.txt
- source/write/replace.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45176>
<li><a href=https://deploy-preview-130--docs-ruby.netlify.app/databases-collections/run-command>databases-collections/run-command</a></li><li><a href=https://deploy-preview-130--docs-ruby.netlify.app/databases-collection>databases-collection</a></li><li><a href=https://deploy-preview-130--docs-ruby.netlify.app/write/delete>write/delete</a></li><li><a href=https://deploy-preview-130--docs-ruby.netlify.app/write/replace>write/replace</a></li>
> DOCSP-45176: Run a command

- source/aggregation.txt
- source/includes/aggregation.rb
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45207>
<li><a href=https://deploy-preview-131--docs-ruby.netlify.app/aggregation>aggregation</a></li><li><a href=https://deploy-preview-131--docs-ruby.netlify.app/index>index</a></li>
> DOCSP-45207 Transform data with aggregation

- source/connect.txt
- source/connect/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45812>
<li><a href=https://deploy-preview-132--docs-ruby.netlify.app/connect/connection-options>connect/connection-options</a></li><li><a href=https://deploy-preview-132--docs-ruby.netlify.app/connect>connect</a></li>
> DOCSP-45812 Connection Options

- source/index.txt
- source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45211>
<li><a href=https://deploy-preview-134--docs-ruby.netlify.app/upgrade>upgrade</a></li><li><a href=https://deploy-preview-134--docs-ruby.netlify.app/index>index</a></li>
> DOCSP-45211 Upgrade major versions

- source/security.txt
- source/security/in-use-encryption.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46860
Essentially the same as other drivers' In-Use Encryption page, like [PHP](https://www.mongodb.com/docs/php-library/current/security/in-use-encryption/)
<li><a href=https://deploy-preview-138--docs-ruby.netlify.app/security/in-use-encryption>security/in-use-encryption</a></li><li><a href=https://deploy-preview-138--docs-ruby.netlify.app/security>security</a></li>
> DOCSP-46860: In-use encryption

- source/includes/monitoring/monitoring.rb
- source/index.txt
- source/monitoring.txt
- source/monitoring/cluster-monitoring.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45201>
<li><a href=https://deploy-preview-133--docs-ruby.netlify.app/monitoring>monitoring</a></li><li><a href=https://deploy-preview-133--docs-ruby.netlify.app/monitoring/cluster-monitoring>monitoring/cluster-monitoring</a></li><li><a href=https://deploy-preview-133--docs-ruby.netlify.app/index>index</a></li>
> DOCSP-45201 Cluster monitoring

- source/connect.txt
- source/connect/csot.txt
- source/includes/connect/csot.rb
- source/indexes/atlas-search-index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42104>
<li><a href=https://deploy-preview-136--docs-ruby.netlify.app/connect/csot>connect/csot</a></li><li><a href=https://deploy-preview-136--docs-ruby.netlify.app/connect>connect</a></li><li><a href=https://deploy-preview-136--docs-ruby.netlify.app/indexes/atlas-search-index>indexes/atlas-search-index</a></li>
> DOCSP-42104 CSOT

- source/data-formats/bson.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44433
<li><a href=https://deploy-preview-142--docs-ruby.netlify.app/data-formats/bson>data-formats/bson</a></li>
> DOCSP-44433: Compare BSON::Binary objects

- source/reference/search-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46398>
https://deploy-preview-144--docs-ruby.netlify.app/reference/search-indexes/
> DOCSP-46398 Fix Atlas Search Create Ex

- source/security/auth-mechanisms/scram.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48720>
> DOCSP-48720 Update non-MongoDB credentials

- source/reference/driver-compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
<li><a href=https://deploy-preview-155--docs-ruby.netlify.app/tutorials/bson>tutorials/bson</a></li><li><a href=https://deploy-preview-155--docs-ruby.netlify.app/getting-started>getting-started</a></li><li><a href=https://deploy-preview-155--docs-ruby.netlify.app/index>index</a></li><li><a href=https://deploy-preview-155--docs-ruby.netlify.app/reference/aggregation>reference/aggregation</a></li><li><a href=https://deploy-preview-155--docs-ruby.netlify.app/reference/connection-and-configuration>reference/connection-and-configuration</a></li><li><a href=https://deploy-preview-155--docs-ruby.netlify.app/reference/create-client>reference/create-client< …
> [Backport V2.20] DOCSP-50028 Remove EOL mentions

- source/aggregation.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50755
<li><a href=https://deploy-preview-157--docs-ruby.netlify.app/aggregation>aggregation</a></li>
> DOCSP-50755: Aggregation links

- snooty.toml
- source/connect.txt
- source/connect/connection-options.txt
- source/connect/network-compression.txt
- source/includes/connect/network-compression.rb
JIRA - https://jira.mongodb.org/browse/DOCSP-51416
<li><a href=https://deploy-preview-162--docs-ruby.netlify.app/connect/network-compression>connect/network-compression</a></li><li><a href=https://deploy-preview-162--docs-ruby.netlify.app/connect>connect</a></li><li><a href=https://deploy-preview-162--docs-ruby.netlify.app/connect/connection-options>connect/connection-options</a></li>
> DOCSP-51416 Network Compression
