config/redirects

Adds redirect rules for new branch, v2.18

add redirect for new branch

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.15

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.14

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.12

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.3

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.11

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.8

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.7

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.0

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.4

---

conf.py
config/intersphinx.yaml

DOCSP-30725: EOL v2.5

---

.gitmodules
config/redirects
snooty.toml
worker.sh

Similar to https://github.com/mongodb/docs-ruby/pull/45

Fixes for Snooty build v2.17

---

.gitmodules
config/redirects
snooty.toml
worker.sh

Similar to https://github.com/mongodb/docs-ruby/pull/45

Fixes for Snooty build v2.16

---

.gitmodules

I'll be making the relevant updates in the docs-worker-pool Makefile to move the files into the right position, but they need to be in the repo to move them 😁

DOP-4013: add bson-ruby submodule to access its tutorial

---

.gitmodules

For reviewer:
Check that the "DOCSP-32949: docs link to the BSON 4.x Tutorial" is included in the submodule commit diff list.

DOCSP-32949 v2.18 submodule update

---

config/redirects

JIRA - https://jira.mongodb.org/browse/DOCSP-38137

DOCSP-38137: v2.20 Updates

---

source/reference/create-client.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42139
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/ruby-driver/DOCSP-42139-read-concern-vals/reference/create-client/#ruby-options

DOCSP-42139: Update read concern values

---

config/redirects
source/reference/driver-compatibility.txt
source/release-notes.txt

Compat table was already updated.
JIRA - <https://jira.mongodb.org/browse/DOCSP-43707>
https://deploy-preview-73--docs-ruby.netlify.app/reference/driver-compatibility/
https://deploy-preview-73--docs-ruby.netlify.app/release-notes/

DOCSP-43707: 2.21 changes

---

source/reference/crud-operations.txt

Jira - https://jira.mongodb.org/browse/DOCSP-42967
Staging - https://deploy-preview-81--docs-ruby.netlify.app/reference/crud-operations/#reading

Removing nested note from table

---

snooty.toml
source/includes/write/delete.rb
source/write/delete.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-45189>
<li><a href=https://deploy-preview-104--docs-ruby.netlify.app/write/delete>write/delete</a></li>

DOCSP-45189: Delete

---

source/includes/read/distinct.rb
source/read.txt
source/read/distinct.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-45198
<li><a href=https://deploy-preview-111--docs-ruby.netlify.app/read/distinct>read/distinct</a></li><li><a href=https://deploy-preview-111--docs-ruby.netlify.app/read>read</a></li>

DOCSP-45198: Distinct values

---

source/includes/write/bulk-write.rb
source/write/bulk-write.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-45190>
<li><a href=https://deploy-preview-116--docs-ruby.netlify.app/write/bulk-write>write/bulk-write</a></li>

DOCSP-45190: Bulk Write

---

source/reference/create-client.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
<li><a href=https://deploy-preview-126--docs-ruby.netlify.app/reference/create-client>reference/create-client</a></li>

[Ruby] Format Issue on Ruby v2.21 Create a Client Page

---

snooty.toml

JIRA - <https://jira.mongodb.org/browse/DOCSP-48300>
No pages to preview

DOCSP-48300: Update snooty title

---

.github/pull_request_template.md

JIRA - <https://jira.mongodb.org/browse/DOCSP-48931>
No pages to preview

[Ruby] Add a PR checklist item for checking page titles

---

source/connect/connection-targets.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-48763
<li><a href=https://deploy-preview-147--docs-ruby.netlify.app/connect/connection-targets>connect/connection-targets</a></li>

DOCSP-48763 Add docker note

---

source/connect.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-48549
<li><a href=https://deploy-preview-149--docs-ruby.netlify.app/connect>connect</a></li>

DOCSP-48549 AWS Lambda to TOC

---

source/crud/transactions.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-51415
https://deploy-preview-161--docs-ruby.netlify.app/crud/transactions/#causal-consistency

DOCSP-51415 Add causal consistency section

---

source/read.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-51420>
<li><a href=https://deploy-preview-165--docs-ruby.netlify.app/read>read</a></li>
<li><a href=https://deploy-preview-165--docs-ruby.netlify.app/read/cursors/>read/cursors</a></li>

[Ruby] Cursor TOC update

---

source/crud/query.txt

Adding #165 to comp-cov branch

change TOC name (#165)
